### ISSUE TITLE
Implement correct list of Auth0 scopes and permissions

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#4]
## Overview
After much [reading](https://auth0.com/docs/architecture-scenarios/application/spa-api/part-2#configure-the-authorization-extension) about Auth0 best practices, and the ways to configure scopes, and [validating correct scopes are requested](https://auth0.com/docs/scopes/current#limiting-api-scopes-being-issued) for each User Role, we are ready to fully implement the end solution. This ticket will cover the work related to the scopes, permissions, and related rules to correctly assign. 

## Requirements

NOTE: this took me  reading through Auth0 docs a few times when reading about scopes, and authorization permissions. 
`scopes = permissions`
Perhaps should have been obvious when docs saying permission name needs to match the scope name. Also, it is important that the scopes created are in the format `verb:object`. You can see this becomes important in the [example rule](https://auth0.com/docs/architecture-scenarios/application/spa-api/part-2#define-permissions) created that automatically adds the correct permissions (scopes) to the User's id token. 

- We will define the list of scopes that cover the basic operations that users will be able to perform on the site, as well as administrators
- Create scopes in Auth0, and corresponding permissions in authorization extension.
- Assign perms to `Administrator` and `User` Roles
- Ensure `Validate Access Token Scopes` Rule is production ready, and copy to github for source control

### Optional 
Define a script to use Auth0 API to create scopes and permissions to make management easier within multiple tenants.

### Scopes List
I think to keep the list of scopes somewhat manageable that we can use a "create" scope to represent both the create and edit functions. We'll have two Roles

#### User Permissions
I don't think there is a need for a scope to allow the user to edit their own profile, I think that should be implied by the nature of having an access token. Once we create the concept of actual "tags" then we can add scopes in at that time. 
- create:characters
- delete:characters
- create:games
- delete:games
- create:posts - this can cover both posting in lounge forums and actual games
- delete:posts
- view:gamelabels

#### Admin Permissions
I don't think we need scope for games_labels for now as those will be inserted via migrations for now. 
- create:users
- delete:users

## Task List

- [x] Determine if we want to [return User Role(s)](https://auth0.com/docs/extensions/authorization-extension/v2/rules#add-custom-claims-to-the-issued-token) as part of the id_token. 
- [x] Finalize Login providers and create test/prod apps (ie. Google, FB, twitch), etc
- [x] Finalize list of scopes needed for MVP
- [x] Create top-level `auth0` folder in project with subfolder for rules, and README to explain
- [x] Implement scopes and permissions for all Auth0 tenants

**Comment by nazar** [comment]
@mikelax is there a situation when a User will have some User level scopes and not others? i.e. would have `create:characters` scope but not say something like `create:games` and `create:posts`?

**Comment by mikelax** [comment]
@nazar  I have thought about it and am having a hard time coming up with a use case. 
The closest one I can think of is if we have a "Pro" (ie. paid) plan that lets Pro users create games, and regular users can only join games. 

there could be other features like, i think that would be tied to a User "Plan", which would probably be stored in the app_metadata attribute of the id_token.

**Comment by mikelax** [comment]
@nazar  what do you think about the initial list of scopes for the User and Admin?

**Comment by nazar** [comment]
>The closest one I can think of is if we have a "Pro" (ie. paid) plan that lets Pro users create games, and regular users can only join games.

Yep - I was thinking that will apply. Also maybe a scenario for banning?

>what do you think about the initial list of scopes for the User and Admin?

Scopes looks good. The only thing that comes to mind is whether the `create:*` scopes overlap with the `delete:*` scopes - i.e. a create covers create, edit and delete? I'm still not 100%.

**Comment by mikelax** [comment]
@nazar  i think for delete we'll keep separate scopes. 
ie. I could see a scenario where games can never be deleted by a regular user, only archived....still thinking about that one. so for now we'll include create and delete.

**Comment by mikelax** [comment]
Will move determine final list of login providers to a separate ticket as its separate from this task.

**Comment by mikelax** [comment]
Resolved with #15

**Comment by nazar** [comment]
Hey @mikelax,

I'm getting a `Error: Configuration property "auth0.domain" is not defined` on the API. Where should I define this value?
